# Release 发行版本部署
## 多端部署
name: Build Release

on:
  push:
    tags:
      - v*

jobs:
  # 检出 Git 仓库
  common-steps:
    runs-on: windows-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4.1.1
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "18.x"
      - name: Copy .env.example
        run: |
          if (-not (Test-Path .env)) {
            Copy-Item .env.example .env
          } else {
            Write-Host ".env file already exists. Skipping the copy step."
          }

  # Windows
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    needs: common-steps
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Build Electron App for Windows
        run: npm run build:win || true
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: SPlarer-Win
          if-no-files-found: ignore
          path: |
            dist/*.exe
            dist/*.msi
            dist/latest.yml
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          if-no-files-found: ignore
          files: |
            dist/*.exe
            dist/*.msi
            dist/latest.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  # Mac
  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    needs: common-steps
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Build Electron App for macOS
        run: npm run build:mac || true
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: SPlarer-Macos
          if-no-files-found: ignore
          path: |
            dist/*.dmg
            dist/*.zip
            dist/latest-mac.yml
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          if-no-files-found: ignore
          files: |
            dist/*.dmg
            dist/*.zip
            dist/latest-mac.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  # Linux
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-22.04
    needs: common-steps
    steps:
      - name: Ubuntu Update with sudo
        run: sudo apt-get update
      - name: Install Dependencies
        run: npm install
      - name: Build Electron App for Linux
        run: npm run build:linux || true
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: SPlarer-Linux
          if-no-files-found: ignore
          path: |
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/latest-linux.yml
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          if-no-files-found: ignore
          files: |
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/latest-linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
